### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat '...\ts-simple-type\rollup.config.js'

### ISSUE THREAD

**Issue by tyleo** [runem/ts-simple-type#6]
When npm installing this project I'm met with the following error message:

```
Error: ENOENT: no such file or directory, lstat '...\ts-simple-type\rollup.config.js'
    at Object.realpathSync (fs.js:1456:7)
    at runRollup (...\ts-simple-type\node_modules\rollup\bin\rollup:1944:29)
    at Object.<anonymous> (...\ts-simple-type\node_modules\rollup\bin\rollup:2008:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

Does a rollup.config.js need to be checked in?

**Comment by runem** [comment]
Hi Tyler, thanks for making me aware of this problem!

I have now checked in "rollup.config.js", so hopefully it should work now 🤞
